### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by ArcaneWater** [agentE/coc-api-wordpress-smartcode#1]
How can we install this plugin on wordpress? Just put git clone in wp-contents/plugins? Or?

**Comment by agentE** [comment]
That's one way! The other is to download the code and unzip it into that directory.

**Comment by agentE** [comment]
I also updated the code today to fix a bug. Please grab the new code base.

**Comment by ArcaneWater** [comment]
Thanks i just uploaded tryed it says malformed, i put my token in setting but what to put under 
URL of CoC's Developer API ?

**Comment by agentE** [comment]
The URL for version 1 of Coc's API is: https://api.clashofclans.com/v1

**Comment by ArcaneWater** [comment]
Hmm still displaying malfromed box...Not sure what else i am doing wrong

**Comment by agentE** [comment]
Is there a way to take a screen shot of what you see?

**Comment by ArcaneWater** [comment]
Here http://imgur.com/a/qwv4K

**Comment by agentE** [comment]
The smartcode is caching the data. Without a value in the cache expiration
field it will never garb new data. Put a 1 in that field. Wait a minute and
try again.

**Comment by ArcaneWater** [comment]
Same thing, hmm i tryed both tag with # and without and still displaying malformed.

**Comment by agentE** [comment]
Righty-O! I revamped the plugin to hopefully address your issues. If you are still willing to test this out please download and install the plugin again.

Please save your API key and URL values as they will be deleted.

Once you've installed the new version, please deactivate and activate it a few times.

Let me know how it works for you.

**Comment by ArcaneWater** [comment]
Now it works like a charm! Thanks!
